version: '2'
volumes:
  ibmmq:
    driver: local

services:
  ibmmq:
      image: 'docker.io/ibmcom/mq'
      container_name: ibmmq
      environment:
        - LICENSE=accept
        - MQ_QMGR_NAME=QM1
      ports:
        - '1414:1414'
        - '9443:9443'
      volumes:
        - ibmmq:/data/ibmmq
