version: '2'

services:
  mongoDb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    container_name: mongoDb
