version: '2'
volumes:
  ibmmq:
    driver: local
  oracle-data:
  oracle-backup:

services:
#  ibmmq:
#      image: 'docker.io/ibmcom/mq'
#      environment:
#        - LICENSE=accept
#        - MQ_QMGR_NAME=QM1
#      ports:
#        - '1414:1414'
#        - '9443:9443'
#      volumes:
#        - ibmmq:/data/ibmmq
#      container_name: ibmmq

  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 123456
#      root_user: system
#  docker run --name oracledb -p 1521:1521 -e ORACLE_PASSWORD=123456 gvenzl/oracle-xe

#  mssql:
#    image: mcr.microsoft.com/mssql/server:latest
#    container_name: mssql
#    hostname: mssql
#    restart: always
#    environment:
#      SA_PASSWORD: A!123456
#      ACCEPT_EULA: Y
##    volumes:
##      - mssqlvolume:/var/opt/mssql/data # thư mục lưu DB
##      - ./bk:/var/opt/mssql/backup      # thư  mục chứa file backup
#    ports:
#      - '1433:1433'

#services:
#  grpc-service:
#    build:
#      context: grpc
#      dockerfile: Dockerfile
#    container_name: grpc-service
#    image: sacom-grpc:latest
#    ports:
#      - "9000:9000"

#  orchestrator-service:
#    build:
#      context: orchestrator-service
#      dockerfile: Dockerfile
#    container_name: orchestrator-service
#    image: sacom-orchestrator:latest
#    ports:
#      - "9000:9000"

#  receiver-service:
#    build:
#      context: receiver-service
#      dockerfile: Dockerfile
#    container_name: receiver-service
#    image: sacom-receiver-service:latest
#    ports:
#      - "9002:9002"

#  sender-service:
#    build:
#      context: sender-service
#      dockerfile: Dockerfile
#    container_name: sender-service
#    image: sacom-sender:latest
#    ports:
#      - "9001:9001"

#  orches-service:
#    build:
#      context: orches-service
#      dockerfile: Dockerfile
#    container_name: orches-service
#    image: sacom-orches-service:latest
#    ports:
#      - "9292:9292"