server:
  port: 9298
  undertow.max-http-post-size: 0
  error:
    include-message: always
spring:
  webflux.base-path: /webflux-jpa
  application.name: webflux-jpa
  main.allow-bean-definition-overriding: true
  jackson.default-property-inclusion: non_absent
#  autoconfigure.exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MariaDB103Dialect
        #        query:
        #          plan_cache_max_size: 1
        #          plan_parameter_metadata_max_size: 1
        #        generate_statistics: true
        jdbc:
          batch_size: 1000
          time_zone: UTC
        order_inserts: true
        order_updates: true
        #        batch_versioned_data: true
        use-new-id-generator-mappings: true
    #    open-in-view: false
#  datasource:
    #    url: jdbc:mysql://localhost:3306/sakila
    #    url: jdbc:mysql://localhost:3306/employees
#    url: jdbc:mariadb://localhost:3308/sakila
#    username: root
#    password: 123456
#  r2dbc:
#    url: r2dbc:mariadb://localhost:3308/sakila
#    username: root
#    password: 123456

datasource:
  mssql:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=sakila
    username: sa
    password: A!123456
    dialect: org.hibernate.dialect.SQLServer2012Dialect
  mariadb:
    url: jdbc:mariadb://localhost:3308/sakila
    username: root
    password: 123456
    dialect: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.r2dbc: TRACE
#    org.springframework.r2dbc: DEBUG

    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.data.r2dbc: DEBUG
#    io.r2dbc.mariadb.QUERY: DEBUG # for queries
#    io.r2dbc.mariadb.PARAM: DEBUG # for parameters